### PR TITLE
News feed

### PR DESCRIPTION
**Pull request by AnupamaGarg**
'git fetch --all'
'git checkout news-feed'
'hs -o'
please verify that html and css working fine on news-feed page.

### CODE REVIEW

**Review by Daniel-Brewer — CHANGES_REQUESTED** [review]
Page looks great but I think we'll need to find other videos to use as some of those are going to offend a few folks. The double goodbye and doll head videos would be fine though.

**Review by THATBLADEBOY — CHANGES_REQUESTED** [review]
Good start! To keep things more organized and consistent, lets copy and paste your styling into the section dedicated to your page in the main.css. You will need to add classes to some of your elements to prevent overriding styles on other pages.

Also, be sure to merge with the current master and check your links in the nav on your page. Some were not functioning properly.

**Review by hannahmneal — COMMENTED** [review]
It looks great! You might consider adding a header (<h1>Larry David</h1>) above Navbar to look like the other pages, and a space/empty string needed between "Read" and "More" for all sections, but it isn't necessary. Good work!

**Review by THATBLADEBOY — APPROVED** [review]
SWEEEET

**Review by hannahmneal — APPROVED** [review]

**Pull request merged**
